import type { Media } from '../../payload-types'

// Named sizes generated by the Media collection, smallest first.
const SIZE_ORDER = ['thumbnail', 'card', 'feature', 'wide'] as const

// Build a srcset from the generated WebP sizes so the browser downloads the
// smallest image that fits the slot.
const buildSrcSet = (media: Media): string | undefined => {
  const sizes = media.sizes
  if (!sizes) return undefined
  const entries = SIZE_ORDER.map((key) => sizes[key])
    .filter((s): s is NonNullable<typeof s> => Boolean(s?.url && s?.width))
    .map((s) => `${s.url} ${s.width}w`)
  return entries.length > 0 ? entries.join(', ') : undefined
}

/**
 * Renders an uploaded image as a real <img> with width/height (to avoid layout
 * shift), its mandatory alt, a responsive srcset from the generated WebP sizes,
 * and lazy loading everywhere except the hero. Never a CSS background — crawlers
 * must see it and it must carry an alt.
 */
export const SiteImage = ({
  media,
  className,
  priority = false,
  sizes = '100vw',
}: {
  media: number | Media | null | undefined
  className?: string
  priority?: boolean
  sizes?: string
}) => {
  if (!media || typeof media !== 'object' || !media.url) return null

  const srcSet = buildSrcSet(media)

  return (
    <img
      src={media.url}
      srcSet={srcSet}
      sizes={srcSet ? sizes : undefined}
      alt={media.alt ?? ''}
      width={media.width ?? undefined}
      height={media.height ?? undefined}
      className={className}
      // The hero loads eagerly (it is above the fold); everything else defers.
      loading={priority ? 'eager' : 'lazy'}
      decoding="async"
    />
  )
}
