/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    actualites: Actualite;
    categories: Category;
    'legal-pages': LegalPage;
    media: Media;
    messages: Message;
    users: User;
    'payload-kv': PayloadKv;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media';
    };
  };
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    actualites: ActualitesSelect<false> | ActualitesSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    'legal-pages': LegalPagesSelect<false> | LegalPagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    messages: MessagesSelect<false> | MessagesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    identite: Identite;
    couleurs: Couleur;
    contact: Contact;
    horaires: Horaire;
    reseaux: Reseau;
    menu: Menu;
    'pied-de-page': PiedDePage;
    sauvegardes: Sauvegarde;
    diagnostic: Diagnostic;
  };
  globalsSelect: {
    identite: IdentiteSelect<false> | IdentiteSelect<true>;
    couleurs: CouleursSelect<false> | CouleursSelect<true>;
    contact: ContactSelect<false> | ContactSelect<true>;
    horaires: HorairesSelect<false> | HorairesSelect<true>;
    reseaux: ReseauxSelect<false> | ReseauxSelect<true>;
    menu: MenuSelect<false> | MenuSelect<true>;
    'pied-de-page': PiedDePageSelect<false> | PiedDePageSelect<true>;
    sauvegardes: SauvegardesSelect<false> | SauvegardesSelect<true>;
    diagnostic: DiagnosticSelect<false> | DiagnosticSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Les pages de votre site. Créez-en une, ajoutez-la au menu, puis publiez-la.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  publishedAt?: string | null;
  /**
   * Le titre principal de la page (affiché en haut et proposé pour le menu).
   */
  title: string;
  /**
   * L’adresse de la page sur le site, par ex. « services » pour /services. Remplie automatiquement d’après le titre ; modifiable.
   */
  slug?: string | null;
  /**
   * Choisi à la création pour pré-remplir la page. Modifier ce champ ensuite ne change pas le contenu déjà en place.
   */
  template?: ('blank' | 'services' | 'about' | 'pricing') | null;
  /**
   * Ajoutez, réordonnez et remplissez les blocs qui composent la page.
   */
  layout?:
    | (
        | {
            /**
             * Le grand titre affiché en haut de la bannière.
             */
            heading: string;
            /**
             * Une phrase d’accroche sous le titre.
             */
            subheading?: string | null;
            /**
             * L’image affichée derrière le titre. Le texte alternatif est demandé à l’envoi.
             */
            image?: (number | null) | Media;
            cta?: {
              label?: string | null;
              action?: ('page' | 'phone' | 'email' | 'external') | null;
              page?: (number | null) | Page;
              /**
               * L’adresse complète, par exemple https://exemple.fr.
               */
              url?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            /**
             * Optionnel. Affiché en Titre 2 au-dessus du texte.
             */
            heading?: string | null;
            /**
             * Le paragraphe. Vous pouvez ajouter des sous-titres (Titre 2, Titre 3) et des listes.
             */
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            /**
             * L’image affichée à côté du texte.
             */
            image?: (number | null) | Media;
            imagePosition?: ('right' | 'left') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textImage';
          }
        | {
            /**
             * Affiché en Titre 2 au-dessus des cartes. Ex. : « Nos prestations ».
             */
            heading?: string | null;
            /**
             * Optionnel. Une ou deux phrases sous le titre.
             */
            intro?: string | null;
            /**
             * Une carte par service ou prestation.
             */
            cards?:
              | {
                  title: string;
                  description: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'services';
          }
        | {
            /**
             * Affiché en Titre 2 au-dessus des horaires.
             */
            heading?: string | null;
            /**
             * Optionnel. Ex. : « Fermé les jours fériés ».
             */
            note?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hours';
          }
        | {
            /**
             * Affiché en Titre 2 au-dessus des coordonnées.
             */
            heading?: string | null;
            /**
             * Optionnel. Une phrase invitant à vous contacter.
             */
            intro?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contactDetails';
          }
        | {
            /**
             * Affiché en Titre 2 au-dessus du formulaire.
             */
            heading?: string | null;
            /**
             * Optionnel. Une phrase invitant à écrire.
             */
            intro?: string | null;
            /**
             * La page légale vers laquelle pointe le lien de consentement (créez-la dans « Pages légales »).
             */
            privacyPage?: (number | null) | LegalPage;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contactForm';
          }
        | {
            /**
             * Le message principal. Ex. : « Prêt à démarrer votre projet ? ».
             */
            heading: string;
            /**
             * Optionnel. Une phrase de renfort sous le titre.
             */
            text?: string | null;
            button: {
              label: string;
              action?: ('page' | 'phone' | 'email' | 'external') | null;
              page?: (number | null) | Page;
              /**
               * L’adresse complète, par exemple https://exemple.fr.
               */
              url?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'callToAction';
          }
      )[]
    | null;
  /**
   * Comment cette page apparaît dans les résultats de recherche Google.
   */
  seo?: {
    /**
     * Le titre affiché dans les résultats de recherche et l’onglet du navigateur. Idéalement 50 à 60 caractères. Par défaut : le titre de la page.
     */
    title?: string | null;
    /**
     * Le texte affiché sous le titre dans Google. Visez environ 155 caractères. Par défaut : la description de votre activité.
     */
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Vos images. Glissez-déposez pour en ajouter, recadrez si besoin ; le site génère automatiquement des versions optimisées.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Décrit l’image pour les personnes malvoyantes et s’affiche si l’image ne se charge pas. Obligatoire.
   */
  alt: string;
  /**
   * Texte optionnel affiché sous l’image sur le site.
   */
  caption?: string | null;
  /**
   * Mots-clés pour retrouver l’image (ex. « boutique », « équipe »). Optionnel.
   */
  tags?: string[] | null;
  folder?: (number | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    feature?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    wide?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: number;
  name: string;
  folder?: (number | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: number | FolderInterface;
        }
      | {
          relationTo?: 'media';
          value: number | Media;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: 'media'[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Mentions légales, confidentialité, CGU — pré-remplies depuis votre identité, puis modifiables.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-pages".
 */
export interface LegalPage {
  id: number;
  publishedAt?: string | null;
  /**
   * Choisi à la création pour générer le texte. Le contenu reste ensuite entièrement modifiable.
   */
  type: 'mentions-legales' | 'confidentialite' | 'cgu';
  /**
   * Rempli automatiquement d’après le type. Modifiable.
   */
  title?: string | null;
  /**
   * L’adresse de la page (ex. /mentions-legales). Remplie automatiquement.
   */
  slug?: string | null;
  /**
   * Le texte de la page légale. Relisez-le et complétez les mentions entre crochets.
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Vos actualités. Rédigez, choisissez une rubrique et une image, puis publiez.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "actualites".
 */
export interface Actualite {
  id: number;
  publishedAt?: string | null;
  /**
   * Le titre de l’actualité, affiché en haut de l’article et dans la liste.
   */
  title: string;
  /**
   * L’adresse de l’article, par ex. « ouverture-boutique » pour /actualites/ouverture-boutique. Remplie automatiquement d’après le titre.
   */
  slug?: string | null;
  /**
   * La date affichée sur l’article et servant à ordonner la liste.
   */
  publishedDate?: string | null;
  /**
   * La rubrique de cette actualité. Créez-en dans « Catégories ».
   */
  category?: (number | null) | Category;
  /**
   * L’image de couverture, affichée dans la liste et en haut de l’article.
   */
  image?: (number | null) | Media;
  /**
   * Un court résumé affiché dans la liste des actualités et, à défaut de description SEO, dans les résultats de recherche.
   */
  excerpt?: string | null;
  /**
   * Le corps de l’article. Sous-titres (Titre 2, Titre 3), listes et liens disponibles.
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Comment cette page apparaît dans les résultats de recherche Google.
   */
  seo?: {
    /**
     * Le titre affiché dans les résultats de recherche et l’onglet du navigateur. Idéalement 50 à 60 caractères. Par défaut : le titre de la page.
     */
    title?: string | null;
    /**
     * Le texte affiché sous le titre dans Google. Visez environ 155 caractères. Par défaut : la description de votre activité.
     */
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Les rubriques de vos actualités (ex. « Événements », « Nouveautés »).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  /**
   * Le nom de la rubrique, affiché sur les actualités qui lui sont rattachées.
   */
  name: string;
  /**
   * Rempli automatiquement d’après le nom. Utilisé dans l’adresse des pages.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Les messages reçus via le formulaire de contact du site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages".
 */
export interface Message {
  id: number;
  /**
   * Cochez une fois le message traité.
   */
  read?: boolean | null;
  name: string;
  email: string;
  message: string;
  /**
   * Preuve que la case de consentement a été cochée à l’envoi.
   */
  consent?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Les accès à l’administration. Créez un accès pour un collaborateur, ou révoquez-le sans le supprimer.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Nom affiché de la personne qui administre le site.
   */
  name?: string | null;
  /**
   * L’administrateur gère les accès ; l’éditeur gère uniquement les contenus.
   */
  role: 'admin' | 'editor';
  /**
   * Coché, cette personne ne peut plus se connecter, sans perdre son compte. Décochez pour réactiver.
   */
  disabled?: boolean | null;
  /**
   * Mis à jour automatiquement. Sert au diagnostic de sécurité.
   */
  passwordChangedAt?: string | null;
  /**
   * Se règle via le bouton d’activation ci-dessus, pas à la main.
   */
  twoFactorEnabled?: boolean | null;
  twoFactorSecret?: string | null;
  twoFactorBackupCodes?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'actualites';
        value: number | Actualite;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'legal-pages';
        value: number | LegalPage;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'messages';
        value: number | Message;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: number | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  publishedAt?: T;
  title?: T;
  slug?: T;
  template?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              heading?: T;
              subheading?: T;
              image?: T;
              cta?:
                | T
                | {
                    label?: T;
                    action?: T;
                    page?: T;
                    url?: T;
                  };
              id?: T;
              blockName?: T;
            };
        textImage?:
          | T
          | {
              heading?: T;
              content?: T;
              image?: T;
              imagePosition?: T;
              id?: T;
              blockName?: T;
            };
        services?:
          | T
          | {
              heading?: T;
              intro?: T;
              cards?:
                | T
                | {
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        hours?:
          | T
          | {
              heading?: T;
              note?: T;
              id?: T;
              blockName?: T;
            };
        contactDetails?:
          | T
          | {
              heading?: T;
              intro?: T;
              id?: T;
              blockName?: T;
            };
        contactForm?:
          | T
          | {
              heading?: T;
              intro?: T;
              privacyPage?: T;
              id?: T;
              blockName?: T;
            };
        callToAction?:
          | T
          | {
              heading?: T;
              text?: T;
              button?:
                | T
                | {
                    label?: T;
                    action?: T;
                    page?: T;
                    url?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "actualites_select".
 */
export interface ActualitesSelect<T extends boolean = true> {
  publishedAt?: T;
  title?: T;
  slug?: T;
  publishedDate?: T;
  category?: T;
  image?: T;
  excerpt?: T;
  content?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-pages_select".
 */
export interface LegalPagesSelect<T extends boolean = true> {
  publishedAt?: T;
  type?: T;
  title?: T;
  slug?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  tags?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        feature?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        wide?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages_select".
 */
export interface MessagesSelect<T extends boolean = true> {
  read?: T;
  name?: T;
  email?: T;
  message?: T;
  consent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  disabled?: T;
  passwordChangedAt?: T;
  twoFactorEnabled?: T;
  twoFactorSecret?: T;
  twoFactorBackupCodes?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "identite".
 */
export interface Identite {
  id: number;
  /**
   * Apparaît en haut du site et dans l’onglet du navigateur.
   */
  companyName: string;
  /**
   * Une phrase courte affichée sous le nom, dans l’en-tête.
   */
  slogan?: string | null;
  /**
   * Affiché dans l’en-tête du site. Le texte alternatif est demandé à l’envoi.
   */
  logo?: (number | null) | Media;
  /**
   * Présente votre activité en quelques phrases. Sert aussi de description par défaut dans les moteurs de recherche.
   */
  activityDescription?: string | null;
  /**
   * La dénomination officielle de l’entreprise, reprise dans les mentions légales.
   */
  legalName?: string | null;
  /**
   * Votre numéro SIRET (14 chiffres). Apparaît dans les mentions légales.
   */
  siret?: string | null;
  /**
   * Utilisée pour la fiche établissement affichée aux moteurs de recherche.
   */
  address?: {
    /**
     * Numéro et nom de rue. Ex. : 12 rue des Fleurs.
     */
    street?: string | null;
    postalCode?: string | null;
    city?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "couleurs".
 */
export interface Couleur {
  id: number;
  /**
   * Boutons, liens et éléments mis en avant.
   */
  primary: string;
  /**
   * Accents et éléments complémentaires.
   */
  secondary: string;
  /**
   * La couleur du texte courant sur les fonds clairs.
   */
  text: string;
  /**
   * La couleur de fond des pages.
   */
  background: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact".
 */
export interface Contact {
  id: number;
  /**
   * Affichée comme lien cliquable. Un clic ouvre le logiciel de messagerie du visiteur.
   */
  email?: string | null;
  /**
   * Affiché comme lien cliquable. Sur mobile, un clic lance l’appel.
   */
  phone?: string | null;
  /**
   * L’adresse où l’on peut vous rendre visite, affichée sur la page de contact.
   */
  address?: {
    /**
     * Numéro et nom de rue. Ex. : 12 rue des Fleurs.
     */
    street?: string | null;
    postalCode?: string | null;
    city?: string | null;
  };
  /**
   * Affichés dans le bloc « Contact » d’une page, par exemple « Appelez-nous » ou « Écrivez-nous ».
   */
  ctaButtons?:
    | {
        label: string;
        /**
         * Ce que fait le bouton. « Appeler » et « Écrire » utilisent le téléphone et l’e-mail ci-dessus.
         */
        action: 'phone' | 'email' | 'page';
        /**
         * La page vers laquelle le bouton mène.
         */
        page?: (number | null) | Page;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "horaires".
 */
export interface Horaire {
  id: number;
  /**
   * Pour chaque jour, indiquez « fermé » ou une ou plusieurs plages horaires. Une pause déjeuner se traduit par deux plages.
   */
  week?:
    | {
        day: 'monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday' | 'sunday';
        closed?: boolean | null;
        /**
         * Ex. : de 09:00 à 12:00, puis de 14:00 à 18:00.
         */
        slots?:
          | {
              from: string;
              to: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reseaux".
 */
export interface Reseau {
  id: number;
  /**
   * Affichés dans le pied de page. Laissez vide les réseaux que vous n’utilisez pas.
   */
  links?:
    | {
        platform: 'facebook' | 'instagram' | 'linkedin' | 'x' | 'youtube' | 'tiktok' | 'other';
        /**
         * L’adresse complète, par exemple https://facebook.com/votre-page.
         */
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu".
 */
export interface Menu {
  id: number;
  /**
   * Les liens du menu, dans l’ordre d’affichage. Glissez-déposez pour réordonner.
   */
  items?:
    | {
        /**
         * La page ouverte par cette entrée du menu.
         */
        page: number | Page;
        /**
         * Par défaut, le titre de la page est utilisé. Renseignez pour afficher un texte plus court.
         */
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pied-de-page".
 */
export interface PiedDePage {
  id: number;
  /**
   * Chaque colonne affiche un titre et une liste de liens en bas de chaque page.
   */
  columns?:
    | {
        title: string;
        links?:
          | {
              /**
               * La page ouverte par ce lien.
               */
              page: number | Page;
              /**
               * Par défaut, le titre de la page est utilisé.
               */
              label?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Affichée tout en bas. Laissez vide pour afficher automatiquement « © année + nom de l’entreprise ».
   */
  copyright?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Sauvegardez votre site et restaurez-le en cas de besoin.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sauvegardes".
 */
export interface Sauvegarde {
  id: number;
  /**
   * À quelle fréquence le site se sauvegarde tout seul. Vous pouvez aussi sauvegarder à la main ci-dessous.
   */
  frequency?: ('manual' | 'daily' | 'weekly') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * État de sécurité et de santé du site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "diagnostic".
 */
export interface Diagnostic {
  id: number;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "identite_select".
 */
export interface IdentiteSelect<T extends boolean = true> {
  companyName?: T;
  slogan?: T;
  logo?: T;
  activityDescription?: T;
  legalName?: T;
  siret?: T;
  address?:
    | T
    | {
        street?: T;
        postalCode?: T;
        city?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "couleurs_select".
 */
export interface CouleursSelect<T extends boolean = true> {
  primary?: T;
  secondary?: T;
  text?: T;
  background?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact_select".
 */
export interface ContactSelect<T extends boolean = true> {
  email?: T;
  phone?: T;
  address?:
    | T
    | {
        street?: T;
        postalCode?: T;
        city?: T;
      };
  ctaButtons?:
    | T
    | {
        label?: T;
        action?: T;
        page?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "horaires_select".
 */
export interface HorairesSelect<T extends boolean = true> {
  week?:
    | T
    | {
        day?: T;
        closed?: T;
        slots?:
          | T
          | {
              from?: T;
              to?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reseaux_select".
 */
export interface ReseauxSelect<T extends boolean = true> {
  links?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu_select".
 */
export interface MenuSelect<T extends boolean = true> {
  items?:
    | T
    | {
        page?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pied-de-page_select".
 */
export interface PiedDePageSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              page?: T;
              label?: T;
              id?: T;
            };
        id?: T;
      };
  copyright?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sauvegardes_select".
 */
export interface SauvegardesSelect<T extends boolean = true> {
  frequency?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "diagnostic_select".
 */
export interface DiagnosticSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}